/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/users": {
    /** @description Get All User */
    get: operations["getUsers"];
    /** @description Receive a name in request body and respond with a greeting message for the name informed */
    post: operations["postHello"];
    options: {
      responses: {
        /** @description Default response */
        200: never;
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** HelloRequest */
    UsersRequest: {
      name: string;
    };
    /** HelloResponse */
    UsersResponse: ({
        id: number;
        userName: string;
      })[];
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  /** @description Get All User */
  getUsers: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["UsersResponse"];
        };
      };
    };
  };
  /** @description Receive a name in request body and respond with a greeting message for the name informed */
  postHello: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UsersRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": {
            status: string;
          };
        };
      };
    };
  };
}
